# Generated by Django 5.2.17 on 2026-10-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("balance", models.BigIntegerField(default=0)),
                (
                    "behavior",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("FAIL", "Fail"), ("PENDING", "Pending")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)), name="provider_balance_nonnegative"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("behavior__in", ["NORMAL", "FAIL", "PENDING"])),
                        name="provider_behavior_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("source_account_id", models.CharField(max_length=100)),
                ("destination_account_id", models.CharField(max_length=100)),
                ("amount", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("failure_code", models.CharField(max_length=100, null=True)),
                ("ready_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "PENDING")),
                        fields=["ready_at"],
                        name="provider_due_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="provider_amount_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "IRR")), name="provider_currency_irr"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["PENDING", "SUCCEEDED", "FAILED"])),
                        name="provider_status_valid",
                    ),
                ],
            },
        ),
    ]
