# Generated by Django 5.2.17 on 2026-10-04 06:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
                ("balance", models.BigIntegerField(default=0)),
                ("last_sequence", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)), name="wallet_balance_nonnegative"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_sequence__gte", 0)),
                        name="wallet_sequence_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TopUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("amount", models.BigIntegerField()),
                ("currency", models.CharField(default="IRR", max_length=3)),
                ("source_account_id", models.CharField(max_length=100)),
                ("destination_account_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SETTLED", "Settled"),
                            ("FAILED", "Failed"),
                            ("REVIEW_REQUIRED", "Review Required"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(max_length=100, null=True)),
                ("last_checked_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_ups",
                        to="wallets.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("wallet_sequence", models.BigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")], max_length=6
                    ),
                ),
                ("delta", models.BigIntegerField()),
                ("balance_after", models.BigIntegerField()),
                ("idempotency_key", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "top_up",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entry",
                        to="wallets.topup",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wallets.wallet",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="topup",
            index=models.Index(
                condition=models.Q(("status", "PENDING")), fields=["id"], name="topup_pending_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topup",
            constraint=models.UniqueConstraint(
                fields=("wallet", "idempotency_key"), name="topup_request_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="topup",
            constraint=models.UniqueConstraint(
                fields=("id", "wallet"), name="topup_id_wallet_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="topup",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="topup_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="topup",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "IRR")), name="topup_currency_irr"
            ),
        ),
        migrations.AddConstraint(
            model_name="topup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "SETTLED", "FAILED", "REVIEW_REQUIRED"])
                ),
                name="topup_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="topup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_status__isnull", True),
                    ("provider_status__in", ["PENDING", "SUCCEEDED", "FAILED"]),
                    _connector="OR",
                ),
                name="topup_provider_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["wallet", "-wallet_sequence"], name="ledger_history_idx"),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                fields=("wallet", "wallet_sequence"), name="ledger_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                fields=("wallet", "idempotency_key"), name="ledger_request_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_after__gte", 0)), name="ledger_balance_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("wallet_sequence__gt", 0)), name="ledger_sequence_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("delta__gt", 0),
                        ("idempotency_key__isnull", True),
                        ("kind", "credit"),
                        ("top_up__isnull", False),
                    ),
                    models.Q(
                        ("delta__lt", 0),
                        ("idempotency_key__isnull", False),
                        ("kind", "debit"),
                        ("top_up__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ledger_entry_shape",
            ),
        ),
    ]
